------------------------------
-- SMAZANI TABULEK.
------------------------------


DELETE FROM OMEZENI;
DELETE FROM STAV;
DELETE FROM HRAC;
DELETE FROM HRA;
DELETE FROM TAH;

DROP TABLE OMEZENI;
DROP TABLE STAV;
DROP TABLE HRAC;
DROP TABLE HRA;
DROP TABLE TAH;


------------------------------
-- VYTVORENI NOVYCH TABULEK.
------------------------------


CREATE TABLE OMEZENI (
	ID INTEGER NOT NULL,
	MIN_SIRKA INTEGER NOT NULL,
	MIN_VYSKA INTEGER NOT NULL,
	MIN_VELIKOST_RADY INTEGER NOT NULL,
	MAX_SIRKA INTEGER NOT NULL,
	MAX_VYSKA INTEGER NOT NULL,	
	MAX_VELIKOST_RADY INTEGER NOT NULL,
	
	PRIMARY KEY(ID) 
);

CREATE TABLE STAV (
	ID INTEGER NOT NULL,
	NAZEV VARCHAR(50),
	
	PRIMARY KEY(ID) 
);

CREATE TABLE HRAC (
	ID INTEGER NOT NULL,
	JMENO VARCHAR(255),
	TAH_PRVNI_POCET_VYHER INTEGER NOT NULL,
	TAH_PRVNI_POCET_REMIZ INTEGER NOT NULL,
	TAH_PRVNI_POCET_PROHER INTEGER NOT NULL,
	TAH_DRUHY_POCET_VYHER INTEGER NOT NULL,
	TAH_DRUHY_POCET_REMIZ INTEGER NOT NULL,
	TAH_DRUHY_POCET_PROHER INTEGER NOT NULL,
	
	PRIMARY KEY(ID) 
);

CREATE TABLE HRA (
	ID INTEGER NOT NULL,
	SIRKA INTEGER NOT NULL,
	VYSKA INTEGER NOT NULL,
	VELIKOST_RADY INTEGER NOT NULL,
	ID_STAV INTEGER NOT NULL,
	ID_PRVNI_HRAC INTEGER NOT NULL,
	CAS_PRVNI_HRAC TIMESTAMP(6) NOT NULL,
	ID_DRUHY_HRAC INTEGER NOT NULL,
	CAS_DRUHY_HRAC TIMESTAMP(6) NOT NULL,
	
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_STAV) REFERENCES STAV(ID),
	FOREIGN KEY(ID_PRVNI_HRAC) REFERENCES HRAC(ID),
	FOREIGN KEY(ID_DRUHY_HRAC) REFERENCES HRAC(ID)
);

CREATE TABLE TAH (
	ID INTEGER NOT NULL,
	CAS_TAHU TIMESTAMP(6) NOT NULL,
	ID_AKTUALNI_HRA INTEGER NOT NULL,
	ID_HRAJICI_HRAC INTEGER NOT NULL,
	
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_AKTUALNI_HRA) REFERENCES HRA(ID),
	FOREIGN KEY(ID_HRAJICI_HRAC) REFERENCES HRAC(ID)
);


------------------------------
-- ZAKLADNI DATA PRO TABULKY.
------------------------------


INSERT INTO STAV VALUES (1, 'rozehraná');
INSERT INTO STAV VALUES (2, 'vítězství začínajícího hráče');
INSERT INTO STAV VALUES (3, 'prohra začínajícího hráče');
INSERT INTO STAV VALUES (4, 'remíza');

INSERT INTO OMEZENI VALUES (1, 5, 5, 5, 20, 20, 15);


------------------------------
-- SMAZANI POHLEDU.
------------------------------


DROP VIEW PAPIR;
DROP VIEW VYHRY_ZACINAJICI;
DROP VIEW PROHRY_ZACINAJICI;
DROP VIEW REMIZY;


------------------------------
-- VYTVORENI POHLEDU.
------------------------------


--CREATE OR REPLACE VIEW PAPIR AS
--SELECT column1, column2, ...
--FROM table_name
--WHERE condition;


------------------------------
-- SMAZANI FUNKCI.
------------------------------


------------------------------
-- VYTVORENI FUNKCI.
------------------------------


------------------------------
-- SMAZANI TRIGGERU.
------------------------------


------------------------------
-- VYTVORENI TRIGGERU.
------------------------------